name: tests
on: push
jobs:
  run_tests:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the repository
  uses: actions/setup-java@v1
  java-version: 8//此处的JDK版本要同maven pom.xml文件中一致
    - name: Cache Maven packages
  with:
  path: ~/.m2
  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  restore-keys: ${{ runner.os }}-m2
    - name: Run tests with Maven
  run: mvn -B test --file pom.xml
